User.create(username: "Jonsnow", password: "foobar")
User.create(username: "Arya", password: "foobar")
User.create(username: "Cersei", password: "foobar")
User.create(username: "Robert", password: "foobar")
User.create(username: "William", password: "foobar")
User.create(username: "New User", password: "password")

Mymessage.create(body: "This is the second test message.", user: User.find(1))
Mymessage.create(body: "This is the third test message.", user: User.find(2))
Mymessage.create(body: "How is it going?", user: User.find(3))
Mymessage.create(body: "I love to watch baseball games.", user: User.find(4))
Mymessage.create(body: "Judo is fun.", user: User.find(5))